---
# tasks file for selenese-runner-java

- name: Load platform default variables 
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_system }}.yml"

- name: Make sure install directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ selenese_runner_java_jar_dir }}'
    - '{{ selenese_runner_java_bin_dir }}'

- name: Install selenese-runner.jar
  get_url:
    url: '{{ selenese_runner_java_jar_url }}'
    dest: '{{ selenese_runner_java_jar_dir }}/selenese-runner.jar'
    checksum: '{{ selenese_runner_java_jar_checksums[selenese_runner_java_version] }}'
    mode: '0444'
    owner: '{{ selenese_runner_java_file_owner | default(ansible_user_uid) }}'
    group: '{{ selenese_runner_java_file_group | default(ansible_user_gid) }}'
 
- name: Install `selenese-runner' script
  template:
    src: selenese-runner.j2
    dest: '{{ selenese_runner_java_bin_dir }}/selenese-runner'
    mode: '0555'
    owner: '{{ selenese_runner_java_file_owner | default(ansible_user_uid) }}'
    group: '{{ selenese_runner_java_file_group | default(ansible_user_gid) }}'
